### ISSUE TITLE
Failed to Redirect UDP Connection

### ISSUE THREAD

**Issue by H3arn** [mzz2017/gg#13] opened 2022-04-17 12:06 UTC
UDP conns can't be redirected to my socks5 node, listened by `trojan-go` [v0.10.6](https://github.com/p4gefau1t/trojan-go/releases/tag/v0.10.6).
`gg` says the server doesn't support it.

I tried a transproxy and confirmed that there is no problem with the UDP support of my trojan-go node.

As for `gg`, It runs in this way:
```
❯ gg -vv curl ip.sb
TRAC[0000] Version: 0.2.3                               
TRAC[0000] OS/Arch: linux/amd64                         
TRAC[0000] Using config file: /home/user1/.ggconfig.toml 
TRAC[0000] Config:
no_udp=false
test_node_before_use=true
subscription.link=
subscription.select=first
subscription.cache_last_node=true
node=socks5://localhost:7891
cache.subscription.last_node= 
INFO[0000] Your proxy server does not support UDP, so we will not redirect UDP traffic. 
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 4                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] network: unknown: family: 1, type: 526337    
TRAC[0000] new socket (): pid: 9521, fd 3               
TRAC[0000] syscall.SYS_CONNECT, syscall.SYS_SENDTO: pid: 9521, fd: 3 
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] network: unknown: family: 1, type: 526337    
TRAC[0000] new socket (): pid: 9521, fd 3               
TRAC[0000] syscall.SYS_CONNECT, syscall.SYS_SENDTO: pid: 9521, fd: 3 
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] new socket (udp): pid: 9521, fd 3            
TRAC[0000] close: pid: 9521, fd 3                       
TRAC[0000] network: unknown: family: 1, type: 526337    
TRAC[0000] new socket (): pid: 9522, fd 7               
TRAC[0000] syscall.SYS_CONNECT, syscall.SYS_SENDTO: pid: 9522, fd: 7 
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] network: unknown: family: 1, type: 526337    
TRAC[0000] new socket (): pid: 9522, fd 7               
TRAC[0000] syscall.SYS_CONNECT, syscall.SYS_SENDTO: pid: 9522, fd: 7 
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] network: unknown: family: 1, type: 526337    
TRAC[0000] new socket (): pid: 9522, fd 7               
TRAC[0000] syscall.SYS_CONNECT, syscall.SYS_SENDTO: pid: 9522, fd: 7 
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] close: pid: 9522, fd 7                       
TRAC[0000] new socket (udp): pid: 9522, fd 7            
TRAC[0000] syscall.SYS_CONNECT, syscall.SYS_SENDTO: pid: 9522, fd: 7 
TRAC[0000] syscall.SYS_CONNECT                          
TRAC[0000] handleINet4 (udp): origin: 1.0.0.1:53, after: 127.0.0.1:22545 
TRAC[0000] received udp: 127.0.0.1:40836, tgt: 1.0.0.1:53 
TRAC[0000] hijackDNS: lookup: ip.sb. to 198.18.0.1      
TRAC[0000] received udp: 127.0.0.1:40836, tgt: 1.0.0.1:53 
TRAC[0000] hijackDNS: lookup: ip.sb. to 198.18.0.1      
TRAC[0005] syscall.SYS_CONNECT, syscall.SYS_SENDTO: pid: 9522, fd: 7 
TRAC[0005] syscall.SYS_SENDTO                           
TRAC[0005] received udp: 127.0.0.1:40836, tgt: 1.0.0.1:53 
TRAC[0005] hijackDNS: lookup: ip.sb. to 198.18.0.1      
TRAC[0010] syscall.SYS_CONNECT, syscall.SYS_SENDTO: pid: 9522, fd: 7 
TRAC[0010] syscall.SYS_SENDTO                           
TRAC[0010] received udp: 127.0.0.1:40836, tgt: 1.0.0.1:53 
TRAC[0010] hijackDNS: lookup: ip.sb. to 198.18.0.1      
TRAC[0015] close: pid: 9522, fd 7                       
TRAC[0015] syscall.SYS_CONNECT, syscall.SYS_SENDTO: pid: 9522, fd: 6 
TRAC[0015] socketInfo of socket cannot found: pid: 9522, fd: 6 
TRAC[0015] child 9522 exited                            
TRAC[0015] close: pid: 9521, fd 6                       
TRAC[0015] close: pid: 9521, fd 5                       
curl: (6) Could not resolve host: ip.sb
TRAC[0015] close: pid: 9521, fd 3                       
TRAC[0015] close: pid: 9521, fd 4                       
TRAC[0015] child 9521 exited 
```

Is there anything wrong? 
How to fix this? 
Thanks a lot.

**Comment by H3arn** [comment] 2022-04-17 12:42
Just now I tested the socks5 inbound of `v2ray`.
Same thing happened again.

**Comment by mzz2017** [comment] 2022-04-17 15:05
Thanks for your issue. What is your linux distribution?

**Comment by H3arn** [comment] 2022-04-17 15:17
> Thanks for your issue. What is your linux distribution?

Arch Linux x86_64  
Kernel: 5.17.3-arch1-1

**Comment by H3arn** [comment] 2022-04-17 15:17
> Thanks for your issue. What is your linux distribution?

Arch Linux x86_64  
Kernel: 5.17.3-arch1-1

**Comment by H3arn** [comment] 2022-04-17 16:41
BTW, I installed `gg` from archlinuxcn/gg. Could it be a possible problem?

**Comment by mzz2017** [comment] 2022-04-17 16:43
No. But I maybe know the problem. I will reproduce it these days.

And what is your DNS in /etc/resolv.conf?

**Comment by H3arn** [comment] 2022-04-17 17:37
> No. But I maybe know the problem. I will reproduce it these days.
> 
> And what is your DNS in /etc/resolv.conf?
```
❯ cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 1.0.0.1
```
Anything else to provide?

**Comment by mzz2017** [comment] 2022-04-17 17:38
However, can you use 1.0.0.1 normally without proxy?

**Comment by H3arn** [comment] 2022-04-17 17:57
usually not.
it is often interfered.

**Comment by H3arn** [comment] 2022-04-17 17:59
No.
Before I knew gg, I used to configure a transproxy to proxy DNS requests.

**Comment by mzz2017** [comment] 2022-04-18 11:49
Okay. The problem occurs because the socks5 implementation of gg hasn't supported UDP. So the dns lookup will use it's original server (by default it is defined in /etc/resolv.conf).
I'll add UDP support for gg as soon as possible.

**Comment by H3arn** [comment] 2022-04-18 12:12
Many thanks

**Comment by mzz2017** [comment] 2022-06-04 08:10
Fixed in https://github.com/mzz2017/gg/releases/tag/v0.2.4
Thanks!

**Closed by mzz2017** 2022-06-04 08:10 UTC
